### ISSUE TITLE
TS1 - Select parcel locker for simulation

### ISSUE THREAD

**Issue by t2tato01** [Project-Parcel-Locker-App/api#16]
## Task Description
The user should be able to select which of the five parcel lockers he is interacting

### Things needs to be done

- [ ] GET Fetch the list of locker numbers from the backend 
- [ ] POST Send the selected locker information to the backend
- [ ] 
- [ ] 

### Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Code Refactoring
- [ ] Documentation Update
- [ ] Other (Please specify)

## Requirement Number

**Linked Issues**

If this request is related to or duplicates other issues, please link them here.
