### ISSUE TITLE
TS2 - Enter pickup code

### ISSUE THREAD

**Issue by t2tato01** [Project-Parcel-Locker-App/api#17]
## Task Description
Consumer users should be able to enter a four-character code, which opens the cabinet door. 
The system should indicate this with text “DOOR XX OPEN FOR PICKUP” on the UI.
In addition to the text a button should become visible with text “CLOSE CABINET DOOR”. When the user clicks this button, the pickup operation is assumed to be completed and the parcel status is changed. 
The pickup code is invalidated. The system should recognize if the user has entered incorrect code. The system should recognize if the user entered the correct code, but at incorrect parcel locker.

### Things needs to be done

- [x] 　POST  four-character code
- [x]   The pickup code is invalidated. The system should recognize if the user has entered incorrect code.
- [x]  the system should recognize if the user entered the correct code, but at incorrect parcel locker.

- [x]  POST “CLOSE CABINET DOOR”. 
- [x]   When the user clicks this button, the pickup operation is assumed to be completed and the parcel status is changed. 

### Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Code Refactoring
- [ ] Documentation Update
- [ ] Other (Please specify)

## Requirement Number

**Linked Issues**

If this request is related to or duplicates other issues, please link them here.
