### ISSUE TITLE
R2 - Data storage and loading

### ISSUE THREAD

**Issue by t2tato01** [Project-Parcel-Locker-App/api#25]
## Task Description
The data required by the application should be stored in a server database and accessed by the React application via HTTP interface.

### Things needs to be done

- [ ] think database structure
- [ ] think API structure
- [ ] manage to use typescript
- [ ] connect frontend and backend

### Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Code Refactoring
- [ ] Documentation Update
- [ ] Other (Please specify)

## Requirement Number

**Linked Issues**

If this request is related to or duplicates other issues, please link them here.
