### ISSUE TITLE
R3 - Deployment

### ISSUE THREAD

**Issue by t2tato01** [Project-Parcel-Locker-App/api#26]
## Task Description
The finished application must be available on the public internet.

### Things needs to be done

- [ ] Azure  (see the recording on 07/11)
- [ ]  .env file : https://stackoverflow.com/questions/67383655/how-to-read-env-file-variables-in-nodejs-within-azure-function  
- [ ] 
- [ ] 

### Type of Change

- [ ] Bug Fix
- [x] New Feature
- [ ] Code Refactoring
- [ ] Documentation Update
- [ ] Other (Please specify)

## Requirement Number

**Linked Issues**

If this request is related to or duplicates other issues, please link them here.
